default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch("DS_AUTH_DATABASE_HOST", nil) %>
  password: <%= ENV.fetch("DS_AUTH_DATABASE_PASSWORD", nil) %>
  username: <%= ENV.fetch("DS_AUTH_DATABASE_USERNAME", nil) %>
  pool: <%= ENV.fetch("DS_AUTH_DATABASE_POOL", 5) %>

development:
  <<: *default
  database: ds-auth_development

test:
  <<: *default
  database: ds-auth_test

production:
  <<: *default
  database: ds-auth_production
