default: &default
  adapter: postgresql
  database: <%= ENV.fetch("DS_AUTH_DATABASE_DATABASE", nil) %>
  host: <%= ENV.fetch("DS_AUTH_DATABASE_HOST", nil) %>
  password: <%= ENV.fetch("DS_AUTH_DATABASE_PASSWORD", nil) %>
  username: <%= ENV.fetch("DS_AUTH_DATABASE_USERNAME", nil) %>
  pool: <%= ENV.fetch("DS_AUTH_DATABASE_POOL", 5) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
