default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: defence-solicitor-service-auth_development

test:
  <<: *default
  database: defence-solicitor-service-auth_test

production:
  <<: *default
  database: defence-solicitor-service-auth_production
  username: ds-auth
  password: <%= ENV['DS-AUTH_DATABASE_PASSWORD'] %>
