dsauth:
  app_title: Digital Services Authentication Platform

rails:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
  force_ssl: <%= ENV.fetch("FORCE_SSL", true) %>

devise:
  key: <%= ENV.fetch('DEVISE_KEY') %>
  salt: <%= ENV.fetch('DEVISE_SALT') %>
  session_timeout: <%= ENV.fetch('SESSION_TIMEOUT_MINUTES', 60) %>

doorkeeper:
  force_ssl_in_redirect_uri: <%= ENV.fetch('FORCE_SSL_IN_REDIRECT_URI', true) %>
  session_timeout: <%= ENV.fetch('SESSION_TIMEOUT_MINUTES', 60) %>

action_mailer:
  from_address: <%= ENV.fetch('MAILER_FROM_ADDRESS') %>
  default_url_options:
    host: <%= ENV.fetch('MAILER_DEFAULT_URL_HOST') %>
    port: <%= ENV.fetch('MAILER_DEFAULT_URL_PORT') %>
    protocol: <%= ENV.fetch('MAILER_DEFAULT_URL_PROTOCOL') %>
  smtp_settings:
    address: <%= ENV.fetch('MAILER_SMTP_SERVER') %>
    port: <%= ENV.fetch('MAILER_SMTP_PORT') %>
    authentication: login
    user_name: <%= ENV.fetch('MAILER_SMTP_USER_NAME') %>
    password: <%= ENV.fetch('MAILER_SMTP_PASSWORD') %>
    enable_starttls_auto: true

sentry:
  # Note that this should only be set to false if you absolutely dont care
  # about the security of your environment. This makes error logging vulnerable
  # to man-in-the-middle attacks.
  ssl_verification: <%= ENV.fetch("SENTRY_SSL_VERIFICATION", true) %>
